//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pweb1920.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERDataModelContainer : DbContext
    {
        public ERDataModelContainer()
            : base("name=ERDataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Station> Stations { get; set; }
        public virtual DbSet<ChargingPoint> ChargingPoints { get; set; }
        public virtual DbSet<ChargingMode> ChargingModes { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<PriceHour> PriceHours { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
    }
}
