//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pweb1920.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceHour
    {
        public int Id { get; set; }
        public System.TimeSpan FromTime { get; set; }
        public System.TimeSpan ToTime { get; set; }
        public double Price { get; set; }
    
        public virtual Station Station { get; set; }
    }
}
