//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pweb1920.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Reservation
    {
        public int Id { get; set; }
        public System.TimeSpan TimeStart { get; set; }
        public System.TimeSpan TimeFinish { get; set; }
        public long ServiceCode { get; set; }
        public double EstimatedCost { get; set; }
        public string Status { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ChargingPoint ChargingPoint { get; set; }
        public virtual Client Client { get; set; }
        public virtual ChargingMode ChargingMode { get; set; }

        [NotMapped]
        public bool Selected { get; set; }
    }
}
